#!/usr/bin/env bash

set -x

# ====== Variables =============================

declare -A gaps
declare -A color

gaps["top"]="0"
gaps["bottom"]="0"
gaps["left"]="0"
gaps["right"]="0"
gaps["inner"]="2"

color["focused"]="0xE0808080"
color["normal"]="0x00010101"
color["preselect"]="0xE02d74da"

# Uncomment to refresh ubersicht widget on workspace change
# Make sure to replace WIDGET NAME for the name of the ubersicht widget
#ubersicht_spaces_refresh_command="osascript -e 'tell application id \"tracesOf.Uebersicht\" to refresh widget id \"WIDGET NAME\"'"

# ===== Loading Scripting Additions ============

# See: https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#macos-big-sur---automatically-load-scripting-addition-on-startup
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# ===== Tiling setting =========================

yabai -m config layout bsp

yabai -m config top_padding "${gaps["top"]}"
yabai -m config bottom_padding "${gaps["bottom"]}"
yabai -m config left_padding "${gaps["left"]}"
yabai -m config right_padding "${gaps["right"]}"
yabai -m config window_gap "${gaps["inner"]}"

yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse autoraise

yabai -m config window_topmost off
yabai -m config window_opacity off
yabai -m config window_shadow float

yabai -m config window_border on
yabai -m config window_border_width 2
yabai -m config active_window_border_color "${color["focused"]}"
yabai -m config normal_window_border_color "${color["normal"]}"
yabai -m config insert_feedback_color "${color["preselect"]}"

yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.90
yabai -m config split_ratio 0.50

yabai -m config auto_balance off

yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# ===== Rules ==================================
# 系统设置 -> 桌面与程序坞 -> 切换至应用程序时，切换至含有应用程序打开窗口的空间 -> 关闭
# setting -> Desktop & Docker -> When switch to an application, switch to a space when open application on the window -> off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="macfeh" app="^macfeh$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add app="^System Settings$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="KeePassXC" app="^KeePassXC$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="WeiXin" app="^WeChat$" title=".*" manage=off
yabai -m rule --add app="^WeCom$" title=".*" manage=off
yabai -m rule --add app="^宝盒lite$" title=".*" manage=off
# Idea
yabai -m rule --add app="^IntelliJ IDEA$" title="Settings" manage=off
yabai -m rule --add app="^IntelliJ IDEA$" title="Copy Class" manage=off
yabai -m rule --add app="^IntelliJ IDEA$" title="Add File to Git" manage=off

# ===== Signals ================================

yabai -m signal --add event=application_front_switched action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=display_changed action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=space_changed action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=window_created action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=window_destroyed action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=window_focused action="${ubersicht_spaces_refresh_command}"
yabai -m signal --add event=window_title_changed action="${ubersicht_spaces_refresh_command}"

# 配置软件默认打开桌面
# 注意，需要在系统设置->桌面与程序坞->关闭根据最近使用情况自动排序，否则自动排序后，就不是自己配置的桌面了
# Setting -> Desktop & Dock -> Automatically rearrange Spaces based on most recent use -> off
yabai -m rule --add app="Microsoft Edge" space=^1
yabai -m rule --add app="IntelliJ IDEA" space=^2
yabai -m rule --add app="Code" space=^3
yabai -m rule --add app="Typora" space=^3
yabai -m rule --add app="Microsoft Excel" space=^3
yabai -m rule --add app="Microsoft Word" space=^3
yabai -m rule --add app="iTerm2" space=^4
yabai -m rule --add app="Warp" space=^4
yabai -m rule --add app="Safari" space=^7
yabai -m rule --add app="Music" space=^8
# 设置默认规则：所有未指定的应用启动到空间9
# yabai -m rule --add app="^.*$" space=^9

# 打开系统偏好设置，不使用平铺模式
yabai -m rule --add app="^系统偏好设置$" manage=off
yabai -m rule --add app="^提醒事项$" manage=off
yabai -m rule --add app="^关于本机$" manage=off
yabai -m rule --apply

# 使用信号机制，自动聚焦切换桌面后的窗口 需要：brew install jq
yabai -m signal --add event=space_changed \
  action="yabai -m window --focus \$(yabai -m query --windows --space | jq '.[0].id')"

set +x
printf "yabai: configuration loaded...\\n"

